### PR TITLE
ARM64 added as a supported architecture

### PR DESCRIPTION
**Pull request by bhedouin**

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this @baptiste313.

Before I merge though, can I confirm you've tested the resulting build on an ARM64 linux platform? and, if so, could you confirm the type of machine and operating system you've tested this on?

**Comment by bhedouin** [comment]
Yes, I tested it quickly on a Raspberry Pi and it works fine; I did not encounter any bugs.

**Comment by ssddanbrown** [comment]
@baptiste313 Thanks, to confirm, what PI version and what operating system were you using?

**Comment by bhedouin** [comment]
I use [DietPi](https://dietpi.com/) as my operating system, it's a Debian base.

**Comment by bhedouin** [comment]
I use a Raspberry Pi 4 2Gb

**Pull request closed without merging**
